# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "COMPANY" ("name" VARCHAR NOT NULL,"id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);
create table "COMPUTER" ("name" VARCHAR NOT NULL,"introduced" BIGINT,"discontinued" BIGINT,"companyId" BIGINT,"id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);

# --- !Downs

drop table "COMPANY";
drop table "COMPUTER";

